title : Andrew Colclough
tagline: Who is this? What's your operating number?
author :
  name : Andrew Colclough 
  email : andrew.design@gmail.com
  github : andrewdc
  twitter : wtc
  # feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about/index.md

  
